---
- name: Update apt cache
  apt:
      update_cache: yes
      cache_valid_time: 3600

- name: Install RE Packages
  apt:
      name: "{{ item }}"
      state: present
  with_items: "{{ re_packages }}"
